import io.quarkus.gradle.tasks.QuarkusDev

plugins {
    alias(libs.plugins.quarkus)
    alias(libs.plugins.openrewrite)
}

dependencies {
    implementation libs.jspecify
    implementation enforcedPlatform(libs.quarkus)
    implementation libs.bundles.implementation
    testImplementation libs.bundles.test.implementation
    testImplementation "org.assertj:assertj-core:3.27.7"

    rewrite libs.rewrite.testing.frameworks
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
    jvmArgs("--add-opens", "java.base/java.lang=ALL-UNNAMED")
}

tasks.withType(QuarkusDev).configureEach {
    jvmArgs = ["--add-opens=java.base/java.lang=ALL-UNNAMED"]
}

rewrite {
    activeRecipe('org.openrewrite.java.testing.assertj.JUnitToAssertj')
    activeRecipe("org.openrewrite.java.testing.assertj.Assertj")
    activeRecipe("org.openrewrite.java.testing.hamcrest.MigrateHamcrestToAssertJ")
    setExportDatatables(true)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}